# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorToMap
                                 A QGIS plugin
 Automatically generate custom print layouts from polygon and point layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-20
        copyright            : (C) 2026 by Matheus Durso
        email                : matheusdursonc@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VectorToMap class from file VectorToMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vector_to_map import VectorToMap
    return VectorToMap(iface)
