# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorToMap
                                 A QGIS plugin
 Automatically generate custom print layouts from polygon and point layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Matheus Durso
        email                : matheusdursonc@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt # Necessário para a scrollbar e alinhamento
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QCheckBox, QTableWidgetItem
from qgis.core import (
    QgsProject, 
    QgsPrintLayout, 
    QgsLayoutSize, 
    QgsUnitTypes, 
    QgsLayoutItemMap, 
    QgsLayoutPoint,
    QgsMapLayerProxyModel,
    QgsFeatureRequest,
    QgsSettings
)
from qgis.utils import iface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .vector_to_map_dialog import VectorToMapDialog
import os.path


class VectorToMap:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'VectorToMap_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Vector to Map')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('VectorToMap', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Cria as entradas de menu e ícones na barra de ferramentas."""
        icon_path = ':/plugins/vector_to_map/icon.png'

        # 1. Criamos a ação principal usando o seu helper add_action
        # O self.add_action já cria o QAction, coloca o ícone e conecta ao self.run
        self.action = self.add_action(
            icon_path,
            text='VectorToMap (Atlas & Layout)',
            callback=self.run,
            parent=self.iface.mainWindow())

        # 2. RESOLVENDO O ERRO: Adicionamos ao menu de Vetores do QGIS
        # Aqui passamos a Label (o nome no menu) E a Action (o objeto completo)
        # Isso fará o ícone aparecer igual ao do Plugin Reloader!
        self.iface.addPluginToVectorMenu('Vector to Map', self.action)

        # Controle de primeira execução
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Vector to Map'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Abre a janela de forma persistente (não-modal) e restaura posição/tamanho"""
        from qgis.core import QgsSettings, QgsMapLayerProxyModel
        from qgis.PyQt.QtCore import Qt

        if self.first_start == True:
            self.first_start = False
            self.dlg = VectorToMapDialog()

            # 1. TÍTULO E MEMÓRIA DE GEOMETRIA
            self.dlg.setWindowTitle('VectorToMap (Atlas & Layout)')
            
            settings = QgsSettings()
            geometria = settings.value("/VectorToMap/geometry")
            if geometria:
                self.dlg.restoreGeometry(geometria)
            else:
                self.dlg.resize(500, 700) # Tamanho padrão inicial seguro

            # 2. CONFIGURAÇÕES DE INTERFACE (Scroll e Filtros)
            self.dlg.scrollArea.setWidgetResizable(True)
            self.dlg.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
            self.dlg.mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.VectorLayer)

            # 3. CONEXÕES DE SINAIS
            # Sincroniza atributos ao trocar de camada
            self.dlg.mMapLayerComboBox.layerChanged.connect(self.atualizar_lista_atributos)
            
            # Conexão do 'Marcar Todas' (Usando o nome da função que criamos)
            try:
                self.dlg.chk_selecionar_todos.stateChanged.disconnect()
            except:
                pass
            self.dlg.chk_selecionar_todos.stateChanged.connect(self.marcar_desmarcar_todos)

            # 4. GESTÃO DA JANELA NÃO-MODAL (PERSISTÊNCIA)
            # Desconectamos o fechamento automático padrão do ButtonBox
            try:
                self.dlg.button_box.accepted.disconnect()
            except:
                pass
            
            # Ao clicar em OK: Processa o mapa e SALVA a posição atual
            self.dlg.button_box.accepted.connect(self.processar_clique_ok)
            self.dlg.button_box.accepted.connect(
                lambda: QgsSettings().setValue("/VectorToMap/geometry", self.dlg.saveGeometry())
            )
            
            # Ao Cancelar/Fechar: Salva a posição e fecha a janela
            self.dlg.button_box.rejected.connect(
                lambda: QgsSettings().setValue("/VectorToMap/geometry", self.dlg.saveGeometry())
            )
            self.dlg.button_box.rejected.connect(self.dlg.close)

            # Preenche a lista inicial de atributos
            self.atualizar_lista_atributos()

        # Exibe a janela sem bloquear o restante do QGIS
        self.dlg.show()

    def processar_clique_ok(self):
        """Prepara os dados e o tamanho de página escolhido"""
        camada = self.dlg.mMapLayerComboBox.currentLayer()
        if not camada: return
        
        preset = self.dlg.combo_presets.currentText()
        orientacao = "Retrato" if self.dlg.rb_retrato.isChecked() else "Paisagem"
        tamanho_pg = self.dlg.combo_tamanho_pagina.currentText() # Novo campo
        campo_atlas = self.dlg.combo_atlas.currentData()
        
        # Captura colunas e modos (como já vínhamos fazendo)
        colunas_selecionadas = []
        layout_lista = self.dlg.verticalLayout 
        for i in range(layout_lista.count()):
            w = layout_lista.itemAt(i).widget()
            if isinstance(w, QCheckBox) and w.isChecked():
                colunas_selecionadas.append(w.text())

        modos = {'formulario': self.dlg.chk_modo_formulario.isChecked(),
                 'individual': self.dlg.chk_modo_individual.isChecked()}

        # Lógica de agrupamento
        paginas_dados = []
        if campo_atlas is None:
            for f in camada.getFeatures(): paginas_dados.append({'feicoes': [f], 'valor': None})
        else:
            idx = camada.fields().indexOf(campo_atlas)
            for v in camada.uniqueValues(idx):
                exp = f'"{campo_atlas}" = \'{v}\'' if isinstance(v, str) else f'"{campo_atlas}" = {v}'
                feicoes = list(camada.getFeatures(QgsFeatureRequest().setFilterExpression(exp)))
                if feicoes: paginas_dados.append({'feicoes': feicoes, 'valor': v})
        
        if paginas_dados:
            self.criar_layout_multi_paginas(preset, camada, orientacao, tamanho_pg, paginas_dados, colunas_selecionadas, modos)
    
    def criar_layout_multi_paginas(self, preset, camada, orientacao, tamanho_pg, paginas_dados, colunas, modos):
        """Cria layout com exibição sequencial de todas as feições agrupadas"""
        import re, unicodedata
        from qgis.core import (QgsProject, QgsPrintLayout, QgsLayoutItemMap, QgsLayoutItem,
                               QgsLayoutItemLabel, QgsLayoutItemPage, QgsCoordinateTransform, 
                               QgsLayoutPoint, QgsLayoutSize, QgsUnitTypes, QgsRectangle)
        from qgis.PyQt.QtGui import QFont

        project = QgsProject.instance()
        manager = project.layoutManager()
        
        # 1. NOME DO ARQUIVO PADRONIZADO
        nome_camada = re.sub(r'[^a-zA-Z0-9_]', '_', unicodedata.normalize('NFD', camada.name()).encode('ascii', 'ignore').decode('utf-8'))
        nome_base = f"VectorToMap_{nome_camada}"
        layout_name = nome_base
        contador = 1
        while manager.layoutByName(layout_name):
            layout_name = f"{nome_base}_{contador}"; contador += 1

        layout = QgsPrintLayout(project)
        layout.initializeDefaults() 
        layout.setName(layout_name)
        
        # 2. CONFIGURAÇÃO DE TAMANHO DE PÁGINA
        tamanhos = {'A4': (210, 297), 'A3': (297, 420), 'A2': (420, 594), 'A1': (594, 841), 'A0': (841, 1189)}
        dim = tamanhos.get(tamanho_pg, (210, 297))
        w_pg, h_pg = (dim[1], dim[0]) if orientacao == "Paisagem" else (dim[0], dim[1])
        
        pc = layout.pageCollection()
        pc.pages()[0].setPageSize(QgsLayoutSize(w_pg, h_pg, QgsUnitTypes.LayoutMillimeters))

        margin = 10
        header_h = 35 # Espaço reservado para o cabeçalho no topo

        # 3. LOOP DE PÁGINAS (ATLAS)
        for i, dados in enumerate(paginas_dados):
            if i > 0:
                nova_pg = QgsLayoutItemPage(layout)
                nova_pg.setPageSize(QgsLayoutSize(w_pg, h_pg, QgsUnitTypes.LayoutMillimeters))
                pc.addPage(nova_pg)

            y_offset = i * (h_pg + 10) 
            
            # --- POSICIONAMENTO DO MAPA ---
            if preset == "75% da Altura (Base fixada)":
                w_map, h_map = (w_pg - (2 * margin)), (h_pg - header_h - (2 * margin)) * 0.60
                x_map, y_map = margin, y_offset + margin + header_h
            else: # Mapa Quadrado
                lado = min(w_pg - (2 * margin), (h_pg - header_h) * 0.45)
                w_map = h_map = lado
                x_map, y_map = (w_pg - w_map) / 2, y_offset + margin + header_h

            map_item = QgsLayoutItemMap(layout)
            map_item.setReferencePoint(QgsLayoutItem.UpperLeft)
            map_item.attemptResize(QgsLayoutSize(w_map, h_map, QgsUnitTypes.LayoutMillimeters))
            map_item.attemptMove(QgsLayoutPoint(x_map, y_map, QgsUnitTypes.LayoutMillimeters))
            layout.addLayoutItem(map_item)

            # --- ZOOM PROPORCIONAL (Maior Lado) ---
            ext_unificada = QgsRectangle()
            ext_unificada.setMinimal()
            for f in dados['feicoes']: ext_unificada.combineExtentWith(f.geometry().boundingBox())
            
            trans = QgsCoordinateTransform(camada.crs(), project.crs(), project)
            ext_proj = trans.transformBoundingBox(ext_unificada)
            map_item.setExtent(ext_proj)
            
            mult = 1000 if project.crs().mapUnits() != QgsUnitTypes.DistanceDegrees else 1
            escala = max((ext_proj.width()*mult)/w_map, (ext_proj.height()*mult)/h_map) * 1.3
            map_item.setScale(escala)

            # Trava a geometria
            map_item.attemptResize(QgsLayoutSize(w_map, h_map, QgsUnitTypes.LayoutMillimeters))
            map_item.attemptMove(QgsLayoutPoint(x_map, y_map, QgsUnitTypes.LayoutMillimeters))

            # --- INSERÇÃO SEQUENCIAL DE DADOS ---
            y_dados = y_map + h_map + 5
            limite_y_pagina = y_offset + h_pg - margin
            
            # MODO 1: FORMULÁRIO HTML (Empilhado)
            if modos['formulario'] and colunas:
                texto_completo_html = ""
                for idx, feicao in enumerate(dados['feicoes']):
                    # Adiciona um separador visual entre feições do grupo
                    if len(dados['feicoes']) > 1:
                        texto_completo_html += f"<div style='background-color: #f0f0f0;'><b>ITEM {idx + 1}</b></div>"
                    
                    for col in colunas:
                        valor = str(feicao[col]).strip()
                        texto_completo_html += f"<b>{col}:</b> {valor}<br>"
                    texto_completo_html += "<br>" # Espaço entre feições

                label_f = QgsLayoutItemLabel(layout)
                label_f.setMode(QgsLayoutItemLabel.ModeHtml) 
                label_f.setText(texto_completo_html)
                label_f.setFont(QFont("Arial", 9)) # Fonte levemente menor para caber mais itens
                label_f.attemptMove(QgsLayoutPoint(margin, y_dados, QgsUnitTypes.LayoutMillimeters))
                
                altura_disponivel = limite_y_pagina - y_dados
                label_f.attemptResize(QgsLayoutSize(w_pg - (2*margin), altura_disponivel, QgsUnitTypes.LayoutMillimeters))
                layout.addLayoutItem(label_f)
                y_dados += 30 # Ajuste para não sobrepor se o outro modo estiver ativo

            # MODO 2: CAIXAS INDIVIDUAIS (Sequenciais por Feição)
            if modos['individual'] and colunas:
                for idx, feicao in enumerate(dados['feicoes']):
                    # Se não houver mais espaço na página, interrompe a inserção
                    if y_dados + 15 > limite_y_pagina: break
                    
                    x_ind = margin
                    # Opcional: Adiciona etiqueta de numeração
                    if len(dados['feicoes']) > 1:
                        label_num = QgsLayoutItemLabel(layout); label_num.setText(f"ID {idx+1}:")
                        label_num.setFont(QFont("Arial", 8, QFont.Bold)); label_num.adjustSizeToText()
                        label_num.attemptMove(QgsLayoutPoint(x_ind, y_dados, QgsUnitTypes.LayoutMillimeters))
                        layout.addLayoutItem(label_num)
                        x_ind += label_num.rect().width() + 2

                    for col in colunas:
                        label_i = QgsLayoutItemLabel(layout)
                        label_i.setText(f"{col}: {str(feicao[col]).strip()}")
                        label_i.setFrameEnabled(True); label_i.adjustSizeToText()
                        
                        # Quebra de linha horizontal
                        if x_ind + label_i.rect().width() > (w_pg - margin):
                            x_ind = margin; y_dados += 10
                        
                        if y_dados + 10 > limite_y_pagina: break
                        
                        label_i.attemptMove(QgsLayoutPoint(x_ind, y_dados, QgsUnitTypes.LayoutMillimeters))
                        layout.addLayoutItem(label_i)
                        x_ind += label_i.rect().width() + 4
                    
                    y_dados += 12 # Espaço para a próxima feição do grupo

        layout.refresh()
        manager.addLayout(layout)
        self.iface.openLayoutDesigner(layout)

    def atualizar_lista_atributos(self):
        """Popula os checkboxes e o combo do Atlas, gerenciando a ativação da UI"""
        from qgis.PyQt.QtWidgets import QCheckBox
        
        camada = self.dlg.mMapLayerComboBox.currentLayer()
        layout_destinatario = self.dlg.verticalLayout 
        
        # 1. Limpeza do Layout de Checkboxes (Remove widgets antigos)
        while layout_destinatario.count():
            item = layout_destinatario.takeAt(0)
            if item.widget():
                item.widget().deleteLater()
        
        # 2. Configuração do Checkbox 'Marcar Todas'
        self.dlg.chk_selecionar_todos.blockSignals(True)
        self.dlg.chk_selecionar_todos.setChecked(False)
        self.dlg.chk_selecionar_todos.blockSignals(False)
        
        # Tenta desconectar para evitar múltiplas chamadas se a função for rodada várias vezes
        try:
            self.dlg.chk_selecionar_todos.stateChanged.disconnect()
        except:
            pass
        # Conecta à função que executa a marcação em massa
        self.dlg.chk_selecionar_todos.stateChanged.connect(self.marcar_desmarcar_todos)
        
        # 3. Limpeza e Configuração do Combo do Atlas
        self.dlg.combo_atlas.clear()
        self.dlg.combo_atlas.addItem("--- Sem Agrupamento (Cada Linha) ---", None)

        if not camada:
            self.atualizar_estado_modos_exibicao()
            return

        # 4. Loop de Criação dos Itens por Campo da Camada
        campos = camada.fields()
        for campo in campos:
            nome = campo.name()
            
            # Cria o Checkbox individual
            checkbox = QCheckBox(nome)
            checkbox.setObjectName(f"chk_field_{nome}")
            
            # Conecta às funções de atualização de dados e de validação da UI
            checkbox.stateChanged.connect(self.atualizar_tabela_por_selecao)
            checkbox.stateChanged.connect(self.atualizar_estado_modos_exibicao)
            
            layout_destinatario.addWidget(checkbox)
            
            # Adiciona o campo como opção de agrupamento no Atlas
            self.dlg.combo_atlas.addItem(nome, nome)

        # Adiciona um stretch no final para manter os itens alinhados ao topo
        layout_destinatario.addStretch(1)
        
        # Validação inicial dos botões de modo
        self.atualizar_estado_modos_exibicao()

    
    def atualizar_tabela_por_selecao(self):
        """Atualiza o head(10) apenas com as colunas marcadas nos checkboxes"""
        camada = self.dlg.mMapLayerComboBox.currentLayer()
        tabela = self.dlg.tableWidget
        
        if not camada:
            return

        # 1. Identifica quais colunas foram marcadas
        colunas_selecionadas = []
        layout = self.dlg.verticalLayout
        for i in range(layout.count()):
            widget = layout.itemAt(i).widget()
            if isinstance(widget, QCheckBox) and widget.isChecked():
                # Remove o prefixo 'chk_field_' para ter o nome real da coluna
                colunas_selecionadas.append(widget.text())

        # 2. Configura a estrutura da tabela
        tabela.setColumnCount(len(colunas_selecionadas))
        tabela.setHorizontalHeaderLabels(colunas_selecionadas)
        
        if not colunas_selecionadas:
            tabela.setRowCount(0)
            return

        # 3. Preenche o head(10) com os dados das colunas selecionadas
        num_linhas = min(10, camada.featureCount())
        tabela.setRowCount(num_linhas)
        
        request = QgsFeatureRequest().setLimit(num_linhas)
        for i, feicao in enumerate(camada.getFeatures(request)):
            for j, nome_coluna in enumerate(colunas_selecionadas):
                valor = str(feicao[nome_coluna])
                tabela.setItem(i, j, QTableWidgetItem(valor))
        
        tabela.resizeColumnsToContents()

    def atualizar_estado_modos_exibicao(self):
        """Habilita ou desabilita os modos de exibição com base na seleção"""
        from qgis.PyQt.QtWidgets import QCheckBox
        layout = self.dlg.verticalLayout 
        tem_selecao = False
        
        for i in range(layout.count()):
            widget = layout.itemAt(i).widget()
            if isinstance(widget, QCheckBox) and widget.isChecked():
                tem_selecao = True
                break
        
        # Ativa ou desativa os botões de modo conforme a seleção
        self.dlg.chk_modo_formulario.setEnabled(tem_selecao)
        self.dlg.chk_modo_individual.setEnabled(tem_selecao)
        
        # Desmarca se nada estiver selecionado por segurança
        if not tem_selecao:
            self.dlg.chk_modo_formulario.setChecked(False)
            self.dlg.chk_modo_individual.setChecked(False)

    def marcar_desmarcar_todos(self):
        """Ação do botão 'Marcar Todas' para selecionar a lista e ativar modos"""
        from qgis.PyQt.QtWidgets import QCheckBox
        estado = self.dlg.chk_selecionar_todos.isChecked()
        layout = self.dlg.verticalLayout 
        
        # Percorre os checkboxes e marca/desmarca todos
        for i in range(layout.count()):
            widget = layout.itemAt(i).widget()
            if isinstance(widget, QCheckBox):
                widget.blockSignals(True) # Otimização de performance
                widget.setChecked(estado)
                widget.blockSignals(False)
        
        # Atualiza a lógica de dados e os botões de exibição
        self.atualizar_tabela_por_selecao()
        self.atualizar_estado_modos_exibicao()